"""Rename contractor to business

Revision ID: d7aa47ee743c
Revises: 578399b27b76
Create Date: 2025-08-11 19:57:18.177157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7aa47ee743c'
down_revision: Union[str, Sequence[str], None] = '578399b27b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### Manually adjusted for safe renaming ###

    # Rename the 'contractors' table to 'businesses'
    op.rename_table('contractors', 'businesses')

    # On the 'leads' table, rename the 'contractor_id' column to 'business_id'
    op.alter_column('leads', 'contractor_id', new_column_name='business_id', existing_type=sa.String(length=255))

    # Drop the old foreign key constraint (Alembic may not name it predictably, so we use the autogenerated name)
    op.drop_constraint('leads_contractor_id_fkey', 'leads', type_='foreignkey')

    # Create a new foreign key constraint for the renamed column and table
    op.create_foreign_key('leads_business_id_fkey', 'leads', 'businesses', ['business_id'], ['id'])

    # Clean up the old 'conversations' table if it exists
    # We wrap this in a try/except block to prevent errors if the table was already deleted
    try:
        op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
        op.drop_table('conversations')
    except Exception as e:
        print(f"Could not drop 'conversations' table (it may not exist): {e}")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### Manually adjusted for safe renaming ###

    # Drop the new foreign key constraint
    op.drop_constraint('leads_business_id_fkey', 'leads', type_='foreignkey')

    # Create the old foreign key constraint
    op.create_foreign_key('leads_contractor_id_fkey', 'leads', 'contractors', ['contractor_id'], ['id'])

    # On the 'leads' table, rename the 'business_id' column back to 'contractor_id'
    op.alter_column('leads', 'business_id', new_column_name='contractor_id', existing_type=sa.String(length=255))

    # Rename the 'businesses' table back to 'contractors'
    op.rename_table('businesses', 'contractors')

    # We do not re-create the 'conversations' table on downgrade as it was cleanup.
    # ### end Alembic commands ###
